name: CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      URL_DATABASE: ${{ secrets.URL_DATABASE }}
      USERNAME_DATABASE: ${{ secrets.USERNAME_DATABASE }}
      PASSWORD_DATABASE: ${{ secrets.PASSWORD_DATABASE }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          mvn clean test
