name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn clean package

    - name: Copy files with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc --delete"
        SOURCE: "target"
        REMOTE_HOST: "157.230.84.81"
        REMOTE_USER: "root"
        TARGET: "/root/aplicacao"

    - name: Execute post-deploy script
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 400 key.pem
        ssh -i key.pem -o StrictHostKeyChecking=no root@157.230.84.81 'source /root/post-deploy.sh'
        
        rm key.pem
